import { countBySeverity } from '../core/vulns/findings.js'
import { recommendUpgrades } from '../core/vulns/recommend.js'
import { severityRank } from '../core/vulns/severity.js'
import type {
  CycloneDxSpecVersion,
  DependencyGraph,
  Finding,
  ReadinessCheck,
  ReadinessReport,
  ReadinessStatus,
  ResolvedComponent,
  ResolvedLicense,
  Severity,
} from '../types/index.js'
import { SEVERITY_ORDER, VEX_JUSTIFICATION_TEXT } from '../types/index.js'
import { REPORT_JS } from './behaviour.js'
import { embedJson, escapeHtml, safeUrl } from './escape.js'
import { REPORT_CSS } from './styles.js'

export interface ReportInput {
  graph: DependencyGraph
  findings: readonly Finding[]
  /** Findings a live VEX statement has ruled out. Shown, never hidden. */
  suppressed?: readonly Finding[]
  readiness?: ReadinessReport
  /** ISO 8601 timestamp of the scan. */
  timestamp: string
  offline: boolean
  specVersion: CycloneDxSpecVersion
  /** The SBOM's serial number, so a reader can tie report and SBOM together. */
  serialNumber: string
  toolName: string
  toolVersion: string
}

/**
 * An ordinal glyph per severity, so the rank survives greyscale printing and
 * does not depend on telling red from orange.
 */
const SEVERITY_GLYPH: Record<Severity, string> = {
  critical: '●●●',
  high: '●●○',
  medium: '●○○',
  low: '○○○',
  none: '–',
  unknown: '?',
}

/**
 * Render the whole report as one self-contained HTML document.
 *
 * Self-contained is the requirement that drives everything else: no webfonts, no
 * scripts, no stylesheets from anywhere. The file has to survive being attached
 * to an email and opened from a download folder two years from now.
 */
export function buildReport(input: ReportInput): string {
  const { graph } = input
  const title = `${graph.root.name} ${graph.root.version} — cradle report`

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="generator" content="${escapeHtml(`${input.toolName} ${input.toolVersion}`)}">
<title>${escapeHtml(title)}</title>
<style>${REPORT_CSS}</style>
</head>
<body>
<div class="wrap">
${masthead(input)}
${summarySection(input)}
${readinessSection(input)}
${findingsSection(input)}
${suppressedSection(input)}
${componentsSection(graph)}
${colophon(input)}
</div>
${dataBlock(input)}
<script>${REPORT_JS}</script>
</body>
</html>
`
}

// ---------------------------------------------------------------------------
// Masthead
// ---------------------------------------------------------------------------

function masthead(input: ReportInput): string {
  const { graph } = input
  const facts: [string, string][] = [
    ['Scanned', formatTimestamp(input.timestamp)],
    ['Package manager', graph.packageManager],
    ['Scope', graph.includeDev ? 'All dependencies' : 'Production only'],
    ['Components', String(graph.components.length)],
    ['SBOM format', `CycloneDX ${input.specVersion}`],
    ['SBOM serial', input.serialNumber],
    ['Generated by', `${input.toolName} ${input.toolVersion}`],
  ]
  if (graph.workspaces.length > 0) {
    facts.splice(4, 0, ['Workspaces', graph.workspaces.join(', ')])
  }

  return `<header class="masthead">
<p class="eyebrow">Software bill of materials &amp; vulnerability report</p>
<h1>${escapeHtml(graph.root.name)} <span class="version">${escapeHtml(graph.root.version)}</span></h1>
${graph.root.description === undefined ? '' : `<p class="section-note">${escapeHtml(graph.root.description)}</p>`}
<dl class="facts">
${facts.map(([term, value]) => `  <div><dt>${escapeHtml(term)}</dt><dd${term === 'SBOM serial' ? ' class="mono"' : ''}>${escapeHtml(value)}</dd></div>`).join('\n')}
</dl>
${
  input.offline
    ? `<p class="banner"><strong>Scanned offline.</strong> The component inventory is complete, but no vulnerability lookup was performed. This report says nothing about known vulnerabilities in these components.</p>`
    : ''
}
</header>`
}

// ---------------------------------------------------------------------------
// Summary
// ---------------------------------------------------------------------------

function summarySection(input: ReportInput): string {
  const { graph, findings, offline } = input
  const direct = graph.components.filter((c) => c.direct).length
  const unknownLicence = graph.components.filter((c) => c.licenseUnknown).length
  const withoutFix = findings.filter((f) => f.fixedIn === undefined).length

  const cards = [
    card(
      'Components',
      String(graph.components.length),
      `${direct} direct · ${graph.components.length - direct} transitive`,
    ),
    offline
      ? card('Findings', '—', 'not checked (offline)')
      : card(
          'Findings',
          String(findings.length),
          withoutFix === 0 ? 'all have a fix available' : `${withoutFix} without a fix`,
        ),
    card(
      'Licences',
      String(graph.components.length - unknownLicence),
      unknownLicence === 0 ? 'all components declare one' : `${unknownLicence} undeclared`,
    ),
  ]

  const suppressedCount = (input.suppressed ?? []).length
  if (suppressedCount > 0) {
    cards.push(card('Suppressed', String(suppressedCount), 'ruled out by a VEX statement'))
  }

  return `<section>
<h2>Summary</h2>
<div class="cards">
${cards.join('\n')}
</div>
${offline ? '' : severityBreakdown(findings)}
${recommendationList(findings, offline)}
${licenceBreakdown(graph.components)}
</section>`
}

function card(label: string, value: string, detail: string): string {
  return `  <div class="card"><div class="label">${escapeHtml(label)}</div><div class="value">${escapeHtml(value)}</div><div class="detail">${escapeHtml(detail)}</div></div>`
}

function severityBreakdown(findings: readonly Finding[]): string {
  const counts = countBySeverity(findings)
  const present = SEVERITY_ORDER.filter((severity) => (counts.get(severity) ?? 0) > 0)
  if (present.length === 0) {
    return `<p class="section-note">No known vulnerabilities in the scanned components.</p>`
  }

  const max = Math.max(...present.map((severity) => counts.get(severity) ?? 0))
  return `<ul class="sev-list">
${present
  .map((severity) => {
    const count = counts.get(severity) ?? 0
    const width = Math.round((count / max) * 100)
    return `  <li><span class="sev sev-${severity}" data-glyph="${escapeHtml(SEVERITY_GLYPH[severity])}">${escapeHtml(severity)}</span><span class="num">${count}</span><span class="bar" role="presentation"><span style="width:${width}%"></span></span></li>`
  })
  .join('\n')}
</ul>`
}

function recommendationList(findings: readonly Finding[], offline: boolean): string {
  if (offline) return ''
  const recommendations = recommendUpgrades(findings).slice(0, 5)
  if (recommendations.length === 0) return ''

  return `<h2>Next steps <span class="count">the upgrades that clear the most</span></h2>
<div class="scroll"><table>
<thead><tr><th>Package</th><th>From</th><th>To</th><th>Clears</th><th>Worst</th></tr></thead>
<tbody>
${recommendations
  .map(
    (r) =>
      `  <tr><td><code>${escapeHtml(r.package)}</code> ${r.direct ? '<span class="tag">direct</span>' : '<span class="tag">transitive</span>'}</td><td class="mono">${escapeHtml(r.from)}</td><td class="mono">${escapeHtml(r.to)}</td><td>${r.findingCount}</td><td>${severityMark(r.worstSeverity)}</td></tr>`,
  )
  .join('\n')}
</tbody>
</table></div>`
}

function licenceBreakdown(components: readonly ResolvedComponent[]): string {
  const counts = new Map<string, number>()
  for (const component of components) {
    const label = component.licenseUnknown ? 'undeclared' : licenceLabel(component.licenses)
    counts.set(label, (counts.get(label) ?? 0) + 1)
  }
  if (counts.size === 0) return ''

  const rows = [...counts.entries()].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
  return `<h2>Licences <span class="count">${rows.length} distinct</span></h2>
<div class="scroll"><table>
<thead><tr><th>Licence</th><th>Components</th></tr></thead>
<tbody>
${rows.map(([label, count]) => `  <tr><td>${label === 'undeclared' ? '<em>undeclared</em>' : `<code>${escapeHtml(label)}</code>`}</td><td>${count}</td></tr>`).join('\n')}
</tbody>
</table></div>`
}

// ---------------------------------------------------------------------------
// Findings
// ---------------------------------------------------------------------------

function findingsSection(input: ReportInput): string {
  const { findings, offline } = input

  if (offline) {
    return `<h2>Findings</h2>
<div class="empty">No vulnerability lookup was performed, because the scan ran with <code>--offline</code>. Re-run without it to populate this section.</div>`
  }
  if (findings.length === 0) {
    return `<h2>Findings</h2>
<div class="empty">No known vulnerabilities were reported for these components at the time of the scan. That is a snapshot, not a guarantee — advisories are published continuously.</div>`
  }

  const severities = SEVERITY_ORDER.filter((severity) =>
    findings.some((finding) => finding.severity === severity),
  )

  return `<h2>Findings <span class="count">${findings.length}</span></h2>
<div class="controls" data-controls="findings" hidden>
  <input type="search" data-filter="text" placeholder="Filter by package, ID, or summary" aria-label="Filter findings">
${severities
  .map(
    (severity) =>
      `  <label><input type="checkbox" data-facet="severity" value="${escapeHtml(severity)}"> ${escapeHtml(severity)}</label>`,
  )
  .join('\n')}
  <label><input type="checkbox" data-facet="fix" value="none"> no fix</label>
  <span class="spacer"></span>
  <span class="result-count" data-result-count aria-live="polite"></span>
</div>
<div class="scroll"><table data-table="findings">
<thead><tr>
  <th data-sort="severity">Severity</th>
  <th data-sort="id">Advisory</th>
  <th data-sort="package">Package</th>
  <th data-sort="fixversion">Fixed in</th>
  <th><span class="sr-only">Details</span></th>
</tr></thead>
<tbody>
${findings.map(findingRows).join('\n')}
</tbody>
</table></div>`
}

function findingRows(finding: Finding): string {
  const haystack = [
    finding.id,
    ...finding.aliases,
    finding.component.name,
    finding.component.version,
    finding.summary,
    ...finding.path,
  ]
    .join(' ')
    .toLowerCase()

  const osvUrl = safeUrl(finding.osvUrl)
  const path = finding.path.map((name) => escapeHtml(name)).join('<span class="sep">›</span>')

  const row = `  <tr data-search="${escapeHtml(haystack)}" data-severity="${escapeHtml(finding.severity)}" data-fix="${finding.fixedIn === undefined ? 'none' : 'available'}" data-sort-severity="${severityRank(finding.severity)}" data-sort-id="${escapeHtml(finding.id)}" data-sort-package="${escapeHtml(finding.component.name)}" data-sort-fixversion="${escapeHtml(finding.fixedIn ?? '')}">
    <td>${severityMark(finding.severity)}</td>
    <td>${osvUrl === undefined ? `<code>${escapeHtml(finding.id)}</code>` : `<a href="${escapeHtml(osvUrl)}" rel="noopener noreferrer"><code>${escapeHtml(finding.id)}</code></a>`}${finding.aliases.length === 0 ? '' : `<div class="pathline">${finding.aliases.map((a) => escapeHtml(a)).join(', ')}</div>`}</td>
    <td><code>${escapeHtml(finding.component.name)}</code> <span class="mono">${escapeHtml(finding.component.version)}</span>${finding.component.direct ? ' <span class="tag">direct</span>' : ''}<div class="pathline">${path}</div></td>
    <td>${finding.fixedIn === undefined ? '<span class="tag">no fix</span>' : `<span class="mono">${escapeHtml(finding.fixedIn)}</span>`}</td>
    <td><button type="button" class="disclose" aria-expanded="false" hidden>Details</button></td>
  </tr>`

  return `${row}\n${findingDetail(finding)}`
}

function findingDetail(finding: Finding): string {
  const rows: [string, string][] = []
  if (finding.summary !== '') rows.push(['Summary', escapeHtml(finding.summary)])

  rows.push(['Severity', severityProvenance(finding)])
  if (finding.dependents.length > 0) {
    rows.push([
      'Pulled in by',
      finding.dependents.map((name) => `<code>${escapeHtml(name)}</code>`).join(', '),
    ])
  }
  if (finding.published !== undefined)
    rows.push(['Published', escapeHtml(formatDate(finding.published))])
  if (finding.modified !== undefined)
    rows.push(['Updated', escapeHtml(formatDate(finding.modified))])

  const references = finding.references
    .map((reference) => ({ type: reference.type, url: safeUrl(reference.url) }))
    .filter((reference): reference is { type: string; url: string } => reference.url !== undefined)
    .slice(0, 8)
  if (references.length > 0) {
    rows.push([
      'References',
      `<ul>${references.map((r) => `<li><a href="${escapeHtml(r.url)}" rel="noopener noreferrer">${escapeHtml(r.url)}</a></li>`).join('')}</ul>`,
    ])
  }

  return `  <tr class="detail-row" data-open="false" hidden><td colspan="5">
    <dl class="detail-grid">
${rows.map(([term, value]) => `      <dt>${escapeHtml(term)}</dt><dd>${value}</dd>`).join('\n')}
    </dl>
  </td></tr>`
}

/**
 * Say where the severity came from. A CVSS base score describes a vulnerability
 * in the abstract; whether it is reachable in this project is a separate
 * question, and the report should not blur the two.
 */
function severityProvenance(finding: Finding): string {
  if (finding.cvss !== undefined) {
    return `${escapeHtml(finding.severity)} — CVSS v${escapeHtml(finding.cvss.version)} base score ${escapeHtml(String(finding.cvss.score))} <code>${escapeHtml(finding.cvss.vector)}</code>. This rates the vulnerability in the abstract, not its exploitability here.`
  }
  if (finding.severitySource === 'database') {
    return `${escapeHtml(finding.severity)} — as rated by the advisory database. No CVSS vector this tool can score was published.`
  }
  return 'unknown — the advisory carries neither a scoreable CVSS vector nor a severity rating.'
}

// ---------------------------------------------------------------------------
// CRA readiness
// ---------------------------------------------------------------------------

const STATUS_LABEL: Record<ReadinessStatus, string> = {
  met: 'met',
  partial: 'partial',
  open: 'open',
  'not-assessable': 'not assessable',
}

/** Ordinal marks again, so status never depends on colour. */
const STATUS_GLYPH: Record<ReadinessStatus, string> = {
  met: '✓',
  partial: '~',
  open: '!',
  'not-assessable': '?',
}

/**
 * The readiness checklist.
 *
 * This is the part of the report that is about the regulation rather than the
 * dependency tree, and it is where the wording matters most: every item says
 * what was found and what to do next, and none of them claims that doing so
 * makes anyone compliant.
 */
function readinessSection(input: ReportInput): string {
  const readiness = input.readiness
  if (readiness === undefined || readiness.checks.length === 0) return ''

  const open = readiness.counts.open + readiness.counts.partial
  const summary =
    open === 0
      ? 'Nothing outstanding that cradle can see.'
      : `${open} of ${readiness.checks.length} need attention.`

  return `<h2>CRA readiness <span class="count">${escapeHtml(summary)}</span></h2>
<p class="section-note">The Cyber Resilience Act asks for documentation and process, not only for a clean dependency tree, and that is the part that gets forgotten. Where cradle cannot tell, it says so rather than guessing. None of this is a compliance assessment.</p>
<div class="scroll"><table>
<thead><tr><th>Status</th><th>Check</th><th>Finding and next step</th></tr></thead>
<tbody>
${readiness.checks.map(readinessRow).join('\n')}
</tbody>
</table></div>`
}

function readinessRow(check: ReadinessCheck): string {
  return `  <tr class="ready-${check.status}">
    <td><span class="status status-${check.status}" data-glyph="${escapeHtml(STATUS_GLYPH[check.status])}">${escapeHtml(STATUS_LABEL[check.status])}</span></td>
    <td>${escapeHtml(check.title)}${check.reference === undefined ? '' : `<div class="pathline">${escapeHtml(check.reference)}</div>`}</td>
    <td>${escapeHtml(check.detail)}<div class="pathline"><strong>Next:</strong> ${escapeHtml(check.nextStep)}</div></td>
  </tr>`
}

// ---------------------------------------------------------------------------
// Suppressed findings
// ---------------------------------------------------------------------------

/**
 * Suppressed findings are shown, never hidden.
 *
 * A suppression is a decision someone made and signed their name to, and the
 * whole reason for recording the category is that a reviewer can disagree with
 * it. A report that quietly dropped them would be worth less than one that never
 * had VEX at all.
 */
function suppressedSection(input: ReportInput): string {
  const suppressed = input.suppressed ?? []
  if (suppressed.length === 0) return ''

  return `<h2>Suppressed <span class="count">${suppressed.length}</span></h2>
<p class="section-note">These findings are not counted above, because a VEX statement in this repository rules them out. The category is the auditable part; the note is the reasoning.</p>
<div class="scroll"><table>
<thead><tr><th>Severity</th><th>Advisory</th><th>Package</th><th>Justification</th><th>Expires</th></tr></thead>
<tbody>
${suppressed.map(suppressedRow).join('\n')}
</tbody>
</table></div>`
}

function suppressedRow(finding: Finding): string {
  const suppression = finding.suppression
  const justification = suppression?.justification
  const osvUrl = safeUrl(finding.osvUrl)

  const reason =
    justification === undefined
      ? `<em>${escapeHtml(suppression?.status ?? 'suppressed')}</em>`
      : `<code>${escapeHtml(justification)}</code><div class="pathline">${escapeHtml(VEX_JUSTIFICATION_TEXT[justification])}</div>`
  const note =
    suppression?.notes === undefined
      ? ''
      : `<div class="pathline">${escapeHtml(suppression.notes)}</div>`

  const expiry = renderExpiry(suppression?.expires, suppression?.expiresInDays)

  return `  <tr>
    <td>${severityMark(finding.severity)}</td>
    <td>${osvUrl === undefined ? `<code>${escapeHtml(finding.id)}</code>` : `<a href="${escapeHtml(osvUrl)}" rel="noopener noreferrer"><code>${escapeHtml(finding.id)}</code></a>`}</td>
    <td><code>${escapeHtml(finding.component.name)}</code> <span class="mono">${escapeHtml(finding.component.version)}</span></td>
    <td>${reason}${note}</td>
    <td>${expiry}</td>
  </tr>`
}

function renderExpiry(expires: string | undefined, inDays: number | undefined): string {
  if (expires === undefined) return '<span class="tag">no expiry</span>'
  const date = escapeHtml(formatDate(expires))
  if (inDays === undefined) return `<span class="mono">${date}</span>`
  if (inDays < 0) return `<span class="mono">${date}</span><div class="pathline">lapsed</div>`

  const when = inDays === 0 ? 'today' : inDays === 1 ? 'in 1 day' : `in ${inDays} days`
  return `<span class="mono">${date}</span><div class="pathline">${escapeHtml(when)}</div>`
}

// ---------------------------------------------------------------------------
// Components
// ---------------------------------------------------------------------------

function componentsSection(graph: DependencyGraph): string {
  if (graph.components.length === 0) {
    return `<h2>Components</h2><div class="empty">No dependencies were resolved.</div>`
  }

  return `<h2>Components <span class="count">${graph.components.length}</span></h2>
<div class="controls" data-controls="components" hidden>
  <input type="search" data-filter="text" placeholder="Filter by name, version, or licence" aria-label="Filter components">
  <label><input type="checkbox" data-facet="relationship" value="direct"> direct only</label>
  <label><input type="checkbox" data-facet="licence" value="unknown"> undeclared licence</label>
  <span class="spacer"></span>
  <span class="result-count" data-result-count aria-live="polite"></span>
</div>
<div class="scroll"><table data-table="components">
<thead><tr>
  <th data-sort="name">Name</th>
  <th data-sort="version">Version</th>
  <th data-sort="licence">Licence</th>
  <th data-sort="relationship">Relationship</th>
</tr></thead>
<tbody>
${graph.components.map(componentRow).join('\n')}
</tbody>
</table></div>`
}

function componentRow(component: ResolvedComponent): string {
  const licence = component.licenseUnknown ? 'undeclared' : licenceLabel(component.licenses)
  const haystack = `${component.name} ${component.version} ${licence}`.toLowerCase()
  const relationship = component.direct ? 'direct' : 'transitive'

  const tags = [
    component.workspace ? '<span class="tag">workspace</span>' : '',
    component.dev ? '<span class="tag">dev</span>' : '',
  ]
    .filter((tag) => tag !== '')
    .join(' ')

  return `  <tr data-search="${escapeHtml(haystack)}" data-relationship="${relationship}" data-licence="${component.licenseUnknown ? 'unknown' : 'known'}" data-sort-name="${escapeHtml(component.name)}" data-sort-version="${escapeHtml(component.version)}" data-sort-licence="${escapeHtml(licence)}" data-sort-relationship="${relationship}">
    <td><code>${escapeHtml(component.name)}</code>${tags === '' ? '' : ` ${tags}`}</td>
    <td class="mono">${escapeHtml(component.version)}</td>
    <td>${component.licenseUnknown ? '<em>undeclared</em>' : `<code>${escapeHtml(licence)}</code>`}</td>
    <td>${relationship}</td>
  </tr>`
}

// ---------------------------------------------------------------------------
// Footer and embedded data
// ---------------------------------------------------------------------------

function colophon(input: ReportInput): string {
  return `<footer class="colophon">
<p><strong>This is a technical snapshot, not legal advice.</strong> ${escapeHtml(input.toolName)} documents which components a project ships and which advisories were public for them at the time of the scan. It is not a conformity assessment, not a declaration of conformity, and it does not certify compliance with any regulation.</p>
<p>Findings reflect the advisory databases aggregated by OSV.dev as of ${escapeHtml(formatTimestamp(input.timestamp))}. Advisories are published continuously, so an empty result means "nothing was known then", not "nothing exists".</p>
<p>The machine-readable data behind this page is embedded in it, in the <code>application/json</code> block below, alongside the CycloneDX SBOM written next to this file.</p>
</footer>`
}

/**
 * The same data the page renders, embedded verbatim so the report can be parsed
 * as well as read. A reviewer who receives only this file still has everything.
 */
function dataBlock(input: ReportInput): string {
  return `<script type="application/json" id="cradle-data">
${embedJson({
  tool: { name: input.toolName, version: input.toolVersion },
  project: { name: input.graph.root.name, version: input.graph.root.version },
  timestamp: input.timestamp,
  packageManager: input.graph.packageManager,
  scope: input.graph.includeDev ? 'all' : 'production',
  offline: input.offline,
  sbom: { specVersion: input.specVersion, serialNumber: input.serialNumber },
  components: input.graph.components,
  findings: input.findings,
  suppressed: input.suppressed ?? [],
  readiness: input.readiness ?? null,
})}
</script>`
}

// ---------------------------------------------------------------------------
// Small shared helpers
// ---------------------------------------------------------------------------

function severityMark(severity: Severity): string {
  return `<span class="sev sev-${severity}" data-glyph="${escapeHtml(SEVERITY_GLYPH[severity])}">${escapeHtml(severity)}</span>`
}

function licenceLabel(licenses: readonly ResolvedLicense[]): string {
  if (licenses.length === 0) return 'undeclared'
  return licenses
    .map((license) => {
      if (license.kind === 'id') return license.id
      if (license.kind === 'expression') return license.expression
      return license.name
    })
    .join(', ')
}

/** UTC, spelled out. A report read in another timezone must not shift its date. */
function formatTimestamp(iso: string): string {
  const date = new Date(iso)
  if (Number.isNaN(date.getTime())) return iso
  return `${date.toISOString().replace('T', ' ').slice(0, 19)} UTC`
}

function formatDate(iso: string): string {
  const date = new Date(iso)
  return Number.isNaN(date.getTime()) ? iso : date.toISOString().slice(0, 10)
}
