import type { Strings } from './strings.js'

/** The original wording. Every other locale is measured against this one. */
export const en: Strings = {
  htmlLang: 'en',

  report: {
    title: (project, version) => `${project} ${version} — cradle report`,
    eyebrow: 'Software bill of materials & vulnerability report',
    scanned: 'Scanned',
    packageManager: 'Package manager',
    scope: 'Scope',
    scopeAll: 'All dependencies',
    scopeProduction: 'Production only',
    components: 'Components',
    workspaces: 'Workspaces',
    sbomFormat: 'SBOM format',
    sbomSerial: 'SBOM serial',
    generatedBy: 'Generated by',
    offlineBanner: {
      lead: 'Scanned offline.',
      body: 'The component inventory is complete, but no vulnerability lookup was performed. This report says nothing about known vulnerabilities in these components.',
    },
  },

  summary: {
    heading: 'Summary',
    componentsDetail: (direct, transitive) => `${direct} direct · ${transitive} transitive`,
    findings: 'Findings',
    findingsNotChecked: 'not checked (offline)',
    findingsAllFixable: 'all have a fix available',
    findingsWithoutFix: (count) => `${count} without a fix`,
    licences: 'Licences',
    licencesAllDeclared: 'all components declare one',
    licencesUndeclared: (count) => `${count} undeclared`,
    suppressed: 'Suppressed',
    suppressedDetail: 'ruled out by a VEX statement',
    noVulnerabilities: 'No known vulnerabilities in the scanned components.',
  },

  nextSteps: {
    heading: 'Next steps',
    caption: 'the upgrades that clear the most',
    package: 'Package',
    from: 'From',
    to: 'To',
    clears: 'Clears',
    worst: 'Worst',
  },

  licences: {
    heading: 'Licences',
    distinct: (count) => `${count} distinct`,
    licence: 'Licence',
    components: 'Components',
    undeclared: 'undeclared',
  },

  findings: {
    heading: 'Findings',
    offline:
      'No vulnerability lookup was performed, because the scan ran with <code>--offline</code>. Re-run without it to populate this section.',
    none: 'No known vulnerabilities were reported for these components at the time of the scan. That is a snapshot, not a guarantee — advisories are published continuously.',
    filterPlaceholder: 'Filter by package, ID, or summary',
    filterLabel: 'Filter findings',
    noFix: 'no fix',
    severity: 'Severity',
    advisory: 'Advisory',
    package: 'Package',
    fixedIn: 'Fixed in',
    details: 'Details',
    summary: 'Summary',
    pulledInBy: 'Pulled in by',
    published: 'Published',
    updated: 'Updated',
    references: 'References',
    severityFromCvss: (severity, version, score, vector) =>
      `${severity} — CVSS v${version} base score ${score} <code>${vector}</code>. This rates the vulnerability in the abstract, not its exploitability here.`,
    severityFromDatabase: (severity) =>
      `${severity} — as rated by the advisory database. No CVSS vector this tool can score was published.`,
    severityUnknown:
      'unknown — the advisory carries neither a scoreable CVSS vector nor a severity rating.',
    exploited: 'Exploited',
    knownExploited: 'on CISA KEV',
    knownExploitedSince: (date) => `on CISA KEV since ${date}`,
    epss: (percent, percentile) => `EPSS ${percent}, ${percentile} percentile`,
    noExploitData: 'no data',
    exploitCaption:
      'Whether anyone appears to be exploiting this, which is a different question from how severe it would be. CISA KEV is evidence of exploitation; EPSS is a daily estimate of the probability in the next 30 days. Both are keyed on CVE, so an advisory without one shows no data — which is not the same as no risk.',
    exploitUnavailable: (sources) =>
      `This column is incomplete: ${sources} could not be reached during the scan.`,
  },

  readiness: {
    heading: 'CRA readiness',
    caption:
      'The Cyber Resilience Act asks for documentation and process, not only for a clean dependency tree, and that is the part that gets forgotten. Where cradle cannot tell, it says so rather than guessing. None of this is a compliance assessment.',
    nothingOutstanding: 'Nothing outstanding that cradle can see.',
    needAttention: (open, total) => `${open} of ${total} need attention.`,
    status: 'Status',
    check: 'Check',
    findingAndNextStep: 'Finding and next step',
    next: 'Next:',
  },

  profile: {
    caption: (title, version, date) => `${title} version ${version}, dated ${date}.`,
    notAConformityAssessment:
      'This compares the data fields of the SBOM opposite against the ones the guideline lists. It is <strong>not a conformity assessment</strong>, and several of the guideline’s requirements are about your build process rather than about this file. Where cradle cannot know an answer it says so rather than guessing.',
    status: 'Status',
    dataField: 'Data field',
    askedFor: 'Asked for',
    detail: 'Detail',
    statusLabel: {
      met: 'Met',
      partial: 'Partially',
      open: 'Open',
      'not-assessable': 'Not assessable',
    },
    requirement: { required: 'required', additional: 'additional', optional: 'optional' },
  },

  suppressed: {
    heading: 'Suppressed',
    caption:
      'These findings are not counted above, because a VEX statement in this repository rules them out. The category is the auditable part; the note is the reasoning.',
    justification: 'Justification',
    expires: 'Expires',
    noExpiry: 'no expiry',
    lapsed: 'lapsed',
    inDays: (days) => (days === 0 ? 'today' : days === 1 ? 'in 1 day' : `in ${days} days`),
  },

  notes: {
    heading: 'Resolution notes',
    caption:
      'Shapes in the lockfile that an SBOM cannot state exactly. None of these is an error, and none is hidden: a dependency left out in silence would leave the counts above looking complete when they are not.',
    what: 'What',
    package: 'Package',
    detail: 'Detail',
    label: {
      'git-dependency': 'Installed from git',
      'local-dependency': 'Installed from a local path',
      'aliased-dependency': 'Installed under another name',
      'patched-dependency': 'Patched by the package manager',
      'unresolved-dependency': 'Declared but not in the lockfile',
      'bundled-dependency': 'Bundled inside its parent',
    },
  },

  components: {
    heading: 'Components',
    none: 'No dependencies were resolved.',
    filterPlaceholder: 'Filter by name, version, or licence',
    filterLabel: 'Filter components',
    directOnly: 'direct only',
    undeclaredLicence: 'undeclared licence',
    name: 'Name',
    version: 'Version',
    licence: 'Licence',
    relationship: 'Relationship',
    direct: 'direct',
    transitive: 'transitive',
    workspace: 'workspace',
    dev: 'dev',
  },

  colophon: {
    disclaimerLead: 'This is a technical snapshot, not legal advice.',
    disclaimerBody: (tool) =>
      `${tool} documents which components a project ships and which advisories were public for them at the time of the scan. It is not a conformity assessment, not a declaration of conformity, and it does not certify compliance with any regulation.`,
    advisorySnapshot: (timestamp) =>
      `Findings reflect the advisory databases aggregated by OSV.dev as of ${timestamp}. Advisories are published continuously, so an empty result means “nothing was known then”, not “nothing exists”.`,
    embeddedData:
      'The machine-readable data behind this page is embedded in it, in the <code>application/json</code> block below, alongside the CycloneDX SBOM written next to this file.',
  },

  severity: {
    critical: 'critical',
    high: 'high',
    medium: 'medium',
    low: 'low',
    none: 'none',
    unknown: 'unknown',
  },

  readinessStatus: {
    met: 'met',
    partial: 'partial',
    open: 'open',
    'not-assessable': 'not assessable',
  },

  markdown: {
    verdictFailing: (count, gate) =>
      `❌ ${count} new ${count === 1 ? 'finding' : 'findings'} ${gate}`,
    thresholdSeverity: (severity) => `at or above ${severity}`,
    thresholdKev: 'known to be exploited',
    thresholdEpss: (percent) => `EPSS at or above ${percent}`,
    thresholdJoin: (parts) =>
      parts.length <= 1 ? (parts[0] ?? '') : `${parts.slice(0, -1).join(', ')} or ${parts.at(-1)}`,
    verdictNewBelowThreshold: (count) =>
      `⚠️ ${count} new ${count === 1 ? 'finding' : 'findings'}, none above the threshold`,
    verdictClean: '✅ Nothing new since the baseline',
    subtitle: (components, manager, scope) => `${components} components · ${manager} · ${scope}`,
    scopeAll: 'all dependencies',
    scopeProduction: 'production only',
    knownFindings: (count) => `**${count}** known ${count === 1 ? 'finding' : 'findings'}`,
    newSinceBaseline: (count) => `**${count}** new since the baseline`,
    ruledOutByVex: (count) => `**${count}** ruled out by VEX`,
    noBaselineYet: '_no baseline yet, so everything counts as new_',
    severity: 'Severity',
    advisory: 'Advisory',
    package: 'Package',
    fixedIn: 'Fixed in',
    noFixYet: '— _no fix yet_',
    truncated: (count) =>
      `_${count} further new ${count === 1 ? 'finding is' : 'findings are'} listed in the report._`,
    resolved: (count) =>
      `${count} baselined ${count === 1 ? 'finding is' : 'findings are'} gone. \`cradle check --baseline\` tidies the file up.`,
    unfixableSummary: (count) =>
      `${count} of the new ${count === 1 ? 'finding has' : 'findings have'} no fix available`,
    unfixableBody:
      'Those need a decision rather than an upgrade. `cradle suppress <id> --justification ' +
      '<category>` records one in `.cradle/vex.json`, where a reviewer can see and disagree with it.',
    artifact: (name) =>
      `The full report, the SBOM and \`findings.json\` are attached to this run as **${name}**.`,
    footer: (tool, version) =>
      `${tool} ${version} — a technical snapshot, not legal advice and not a conformity assessment.`,
  },
}
