/**
 * Generates src/version.generated.ts from package.json so the version we stamp
 * into every SBOM cannot drift from the published one. Runs as part of `build`;
 * test/version.test.ts fails if it was not re-run.
 *
 *   node scripts/gen-version.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs'

const pkg = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'))
writeFileSync(
  new URL('../src/version.generated.ts', import.meta.url),
  `// Generated by scripts/gen-version.mjs from package.json. Do not edit.

export const TOOL_NAME = '${pkg.name}'
export const TOOL_VERSION = '${pkg.version}'
`,
)
console.log(`wrote ${pkg.name}@${pkg.version}`)
