/**
 * Propagates the version in package.json to every other place that carries it.
 *
 * `npm version` bumps exactly one file. Six others repeat the number: the
 * generated constant the tool stamps into SBOMs, the action's default
 * cradle-cli version, the `uses:` tag in the README, the spec and the example
 * workflow, and the recorded session in the demo image. Bumping by hand meant
 * remembering all of them, and the first release attempt found out the hard way
 * that nobody does.
 *
 * Wired into npm's `version` lifecycle, so it runs after the bump and before the
 * commit, and its changes land in that same commit.
 *
 *   node scripts/sync-version.mjs [--check]
 *
 * `--check` reports drift without writing, for use in a test.
 */
import { execFileSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'

const check = process.argv.includes('--check')

const root = new URL('../', import.meta.url)
const pkg = JSON.parse(readFileSync(new URL('package.json', root), 'utf8'))
const { name, version } = pkg

/** Files where a `cradle-cli@vX.Y.Z` reference has to follow the release. */
const TAG_REFERENCES = [
  'README.md',
  'SPEC.md',
  'examples/express-service/.github/workflows/cradle.yml',
]

const changed = []

function update(file, transform) {
  const url = new URL(file, root)
  const before = readFileSync(url, 'utf8')
  const after = transform(before)
  if (after === before) return
  changed.push(file)
  if (!check) writeFileSync(url, after)
}

// The constant the tool stamps into every SBOM and VEX document.
update(
  'src/version.generated.ts',
  () =>
    `// Generated by scripts/sync-version.mjs from package.json. Do not edit.\n\nexport const TOOL_NAME = '${name}'\nexport const TOOL_VERSION = '${version}'\n`,
)

// The action's default cradle-cli version: a pinned action tag has to mean a
// pinned tool.
update('action.yml', (text) =>
  text.replace(/(\n {2}version:\n(?: {4}.*\n)*? {4}default: )'[^']*'/, `$1'${version}'`),
)

for (const file of TAG_REFERENCES) {
  update(file, (text) => text.replace(/cradle-cli@v\d+\.\d+\.\d+/g, `cradle-cli@v${version}`))
}

if (!check) {
  // The demo image embeds a recorded session that starts with the version line.
  execFileSync(process.execPath, [new URL('gen-demo-svg.mjs', import.meta.url).pathname], {
    stdio: 'ignore',
  })
}

if (check) {
  if (changed.length > 0) {
    console.error(`Out of step with package.json ${version}:\n  ${changed.join('\n  ')}`)
    console.error('\nRun `npm run sync-version` to fix.')
    process.exit(1)
  }
  console.log(`every version reference matches ${version}`)
} else {
  console.log(
    changed.length === 0
      ? `every version reference already matched ${version}`
      : `synced to ${version}: ${changed.join(', ')}`,
  )
}
